server:
  port: 8081
  servlet:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
  tomcat:
    uri-encoding: UTF-8
spring:
  profiles:
    path: /www/wwwroot/config/
  datasource:
#    username: root
#    password: 135456200
    username: servers_db_core
    password: zszywXXNBpC6wzw4
    url: jdbc:mysql://dog.yunssss.live:3306/servers_db_core?characterEncoding=utf-8&&serverTimezone=GMT%2B8
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath*:/dao/*.xml
